# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 617)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 110, 201, 203))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.manual_layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.manual_layout.setContentsMargins(11, 11, 11, 11)
        self.manual_layout.setSpacing(6)
        self.manual_layout.setObjectName("manual_layout")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setToolTipDuration(-3)
        self.label_5.setObjectName("label_5")
        self.manual_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setToolTipDuration(-3)
        self.label_6.setObjectName("label_6")
        self.manual_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.lLever = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lLever.setObjectName("lLever")
        self.manual_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lLever)
        self.rLever = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rLever.setObjectName("rLever")
        self.manual_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rLever)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setToolTipDuration(-3)
        self.label_7.setObjectName("label_7")
        self.manual_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setToolTipDuration(-3)
        self.label_9.setObjectName("label_9")
        self.manual_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.lHorizontal = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lHorizontal.setObjectName("lHorizontal")
        self.manual_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lHorizontal)
        self.rHorizontal = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rHorizontal.setObjectName("rHorizontal")
        self.manual_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.rHorizontal)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setToolTipDuration(-3)
        self.label_8.setObjectName("label_8")
        self.manual_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setToolTipDuration(-3)
        self.label_10.setObjectName("label_10")
        self.manual_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.lVertical = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lVertical.setObjectName("lVertical")
        self.manual_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lVertical)
        self.rVertical = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.rVertical.setObjectName("rVertical")
        self.manual_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.rVertical)
        self.lEnable = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.lEnable.setObjectName("lEnable")
        self.manual_layout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lEnable)
        self.rEnable = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.rEnable.setObjectName("rEnable")
        self.manual_layout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.rEnable)
        self.mSet = QtWidgets.QPushButton(self.formLayoutWidget)
        self.mSet.setObjectName("mSet")
        self.manual_layout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.mSet)
        self.manual_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.manual_label.setToolTipDuration(-3)
        self.manual_label.setAlignment(QtCore.Qt.AlignCenter)
        self.manual_label.setObjectName("manual_label")
        self.manual_layout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.manual_label)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 160, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.log_layout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.log_layout.setContentsMargins(11, 11, 11, 11)
        self.log_layout.setSpacing(6)
        self.log_layout.setObjectName("log_layout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.log_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.study = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.study.setObjectName("study")
        self.log_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.study)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.log_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.animal = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.animal.setObjectName("animal")
        self.log_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.animal)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setToolTipDuration(-3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.log_layout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.logging = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.logging.setChecked(True)
        self.logging.setObjectName("logging")
        self.log_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.logging)
        self.start = QtWidgets.QPushButton(self.centralWidget)
        self.start.setGeometry(QtCore.QRect(0, 320, 75, 23))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.centralWidget)
        self.stop.setGeometry(QtCore.QRect(120, 320, 75, 23))
        self.stop.setObjectName("stop")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(210, 110, 437, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mButton8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton8.setObjectName("mButton8")
        self.gridLayout_3.addWidget(self.mButton8, 1, 2, 1, 1)
        self.mButton9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton9.setObjectName("mButton9")
        self.gridLayout_3.addWidget(self.mButton9, 1, 1, 1, 1)
        self.mButton7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton7.setObjectName("mButton7")
        self.gridLayout_3.addWidget(self.mButton7, 1, 3, 1, 1)
        self.mButton10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton10.setObjectName("mButton10")
        self.gridLayout_3.addWidget(self.mButton10, 1, 0, 1, 1)
        self.mButton6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton6.setObjectName("mButton6")
        self.gridLayout_3.addWidget(self.mButton6, 1, 4, 1, 1)
        self.mButton15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton15.setObjectName("mButton15")
        self.gridLayout_3.addWidget(self.mButton15, 2, 0, 1, 1)
        self.mButton12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton12.setObjectName("mButton12")
        self.gridLayout_3.addWidget(self.mButton12, 2, 3, 1, 1)
        self.mButton14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton14.setObjectName("mButton14")
        self.gridLayout_3.addWidget(self.mButton14, 2, 1, 1, 1)
        self.mButton13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton13.setObjectName("mButton13")
        self.gridLayout_3.addWidget(self.mButton13, 2, 2, 1, 1)
        self.mButton11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton11.setObjectName("mButton11")
        self.gridLayout_3.addWidget(self.mButton11, 2, 4, 1, 1)
        self.mButton1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton1.setObjectName("mButton1")
        self.gridLayout_3.addWidget(self.mButton1, 0, 4, 1, 1)
        self.mButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton2.setObjectName("mButton2")
        self.gridLayout_3.addWidget(self.mButton2, 0, 3, 1, 1)
        self.mButton5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton5.setObjectName("mButton5")
        self.gridLayout_3.addWidget(self.mButton5, 0, 0, 1, 1)
        self.mButton3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton3.setObjectName("mButton3")
        self.gridLayout_3.addWidget(self.mButton3, 0, 2, 1, 1)
        self.mButton4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton4.setObjectName("mButton4")
        self.gridLayout_3.addWidget(self.mButton4, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "lever-arena v1.0"))
        self.label_5.setText(_translate("MainWindow", "Left Lever"))
        self.label_6.setText(_translate("MainWindow", "Right Lever"))
        self.label_7.setText(_translate("MainWindow", "Left Horizontal"))
        self.label_9.setText(_translate("MainWindow", "Right Horizontal"))
        self.label_8.setText(_translate("MainWindow", "Left Vertical"))
        self.label_10.setText(_translate("MainWindow", "Right Vertical"))
        self.lEnable.setText(_translate("MainWindow", "Left Enable"))
        self.rEnable.setText(_translate("MainWindow", "Right Enable"))
        self.mSet.setText(_translate("MainWindow", "Set"))
        self.manual_label.setText(_translate("MainWindow", "Manual Control"))
        self.label_2.setText(_translate("MainWindow", "Study"))
        self.label_3.setText(_translate("MainWindow", "Animal #"))
        self.label.setText(_translate("MainWindow", "Logging"))
        self.logging.setText(_translate("MainWindow", "Logging"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.mButton8.setText(_translate("MainWindow", "8"))
        self.mButton9.setText(_translate("MainWindow", "9"))
        self.mButton7.setText(_translate("MainWindow", "7"))
        self.mButton10.setText(_translate("MainWindow", "10"))
        self.mButton6.setText(_translate("MainWindow", "6"))
        self.mButton15.setText(_translate("MainWindow", "15"))
        self.mButton12.setText(_translate("MainWindow", "12"))
        self.mButton14.setText(_translate("MainWindow", "14"))
        self.mButton13.setText(_translate("MainWindow", "13"))
        self.mButton11.setText(_translate("MainWindow", "11"))
        self.mButton1.setText(_translate("MainWindow", "1"))
        self.mButton2.setText(_translate("MainWindow", "2"))
        self.mButton5.setText(_translate("MainWindow", "5"))
        self.mButton3.setText(_translate("MainWindow", "3"))
        self.mButton4.setText(_translate("MainWindow", "4"))

