# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 446)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 241, 371))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.log_layout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.log_layout.setContentsMargins(11, 11, 11, 11)
        self.log_layout.setSpacing(6)
        self.log_layout.setObjectName("log_layout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.log_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.study = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.study.setObjectName("study")
        self.log_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.study)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.log_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.animal = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.animal.setObjectName("animal")
        self.log_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.animal)
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setToolTipDuration(-3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.log_layout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.logging = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.logging.setChecked(False)
        self.logging.setObjectName("logging")
        self.log_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.logging)
        self.lLever = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lLever.setObjectName("lLever")
        self.log_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lLever)
        self.rLever = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.rLever.setObjectName("rLever")
        self.log_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.rLever)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setToolTipDuration(-3)
        self.label_6.setObjectName("label_6")
        self.log_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setToolTipDuration(-3)
        self.label_5.setObjectName("label_5")
        self.log_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lEnable = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.lEnable.setObjectName("lEnable")
        self.log_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lEnable)
        self.rEnable = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.rEnable.setChecked(True)
        self.rEnable.setObjectName("rEnable")
        self.log_layout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.rEnable)
        self.mSuccesses = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.mSuccesses.setObjectName("mSuccesses")
        self.log_layout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.mSuccesses)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setToolTipDuration(-3)
        self.label_7.setObjectName("label_7")
        self.log_layout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.start = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.start.setObjectName("start")
        self.log_layout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.start)
        self.stop = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.stop.setObjectName("stop")
        self.log_layout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.stop)
        self.mSet = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.mSet.setObjectName("mSet")
        self.log_layout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.mSet)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 170, 451, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mButton8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton8.setObjectName("mButton8")
        self.gridLayout_3.addWidget(self.mButton8, 1, 2, 1, 1)
        self.mButton9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton9.setObjectName("mButton9")
        self.gridLayout_3.addWidget(self.mButton9, 1, 1, 1, 1)
        self.mButton7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton7.setObjectName("mButton7")
        self.gridLayout_3.addWidget(self.mButton7, 1, 3, 1, 1)
        self.mButton10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton10.setObjectName("mButton10")
        self.gridLayout_3.addWidget(self.mButton10, 1, 0, 1, 1)
        self.mButton6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton6.setObjectName("mButton6")
        self.gridLayout_3.addWidget(self.mButton6, 1, 4, 1, 1)
        self.mButton15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton15.setObjectName("mButton15")
        self.gridLayout_3.addWidget(self.mButton15, 2, 0, 1, 1)
        self.mButton12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton12.setObjectName("mButton12")
        self.gridLayout_3.addWidget(self.mButton12, 2, 3, 1, 1)
        self.mButton14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton14.setObjectName("mButton14")
        self.gridLayout_3.addWidget(self.mButton14, 2, 1, 1, 1)
        self.mButton13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton13.setObjectName("mButton13")
        self.gridLayout_3.addWidget(self.mButton13, 2, 2, 1, 1)
        self.mButton11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton11.setObjectName("mButton11")
        self.gridLayout_3.addWidget(self.mButton11, 2, 4, 1, 1)
        self.mButton1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton1.setObjectName("mButton1")
        self.gridLayout_3.addWidget(self.mButton1, 0, 4, 1, 1)
        self.mButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton2.setObjectName("mButton2")
        self.gridLayout_3.addWidget(self.mButton2, 0, 3, 1, 1)
        self.mButton5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton5.setObjectName("mButton5")
        self.gridLayout_3.addWidget(self.mButton5, 0, 0, 1, 1)
        self.mButton3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton3.setObjectName("mButton3")
        self.gridLayout_3.addWidget(self.mButton3, 0, 2, 1, 1)
        self.mButton4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mButton4.setObjectName("mButton4")
        self.gridLayout_3.addWidget(self.mButton4, 0, 1, 1, 1)
        self.mReward = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mReward.setObjectName("mReward")
        self.gridLayout_3.addWidget(self.mReward, 3, 0, 1, 1)
        self.mFlush = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mFlush.setObjectName("mFlush")
        self.gridLayout_3.addWidget(self.mFlush, 3, 1, 1, 1)
        self.mAdvance = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mAdvance.setObjectName("mAdvance")
        self.gridLayout_3.addWidget(self.mAdvance, 3, 2, 1, 1)
        self.currentSuccess = QtWidgets.QLCDNumber(self.centralWidget)
        self.currentSuccess.setGeometry(QtCore.QRect(350, 10, 64, 23))
        self.currentSuccess.setObjectName("currentSuccess")
        self.totalSuccess = QtWidgets.QLCDNumber(self.centralWidget)
        self.totalSuccess.setGeometry(QtCore.QRect(350, 40, 64, 23))
        self.totalSuccess.setObjectName("totalSuccess")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(270, 13, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(270, 40, 81, 21))
        self.label_8.setObjectName("label_8")
        self.lLeverPos = QtWidgets.QLCDNumber(self.centralWidget)
        self.lLeverPos.setGeometry(QtCore.QRect(570, 10, 64, 23))
        self.lLeverPos.setObjectName("lLeverPos")
        self.rLeverPos = QtWidgets.QLCDNumber(self.centralWidget)
        self.rLeverPos.setGeometry(QtCore.QRect(570, 40, 64, 23))
        self.rLeverPos.setObjectName("rLeverPos")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(476, 10, 91, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(470, 40, 101, 20))
        self.label_10.setObjectName("label_10")
        self.mLeft = QtWidgets.QPushButton(self.centralWidget)
        self.mLeft.setGeometry(QtCore.QRect(640, 10, 75, 23))
        self.mLeft.setObjectName("mLeft")
        self.mRight = QtWidgets.QPushButton(self.centralWidget)
        self.mRight.setGeometry(QtCore.QRect(640, 40, 75, 23))
        self.mRight.setObjectName("mRight")
        self.formLayoutWidget_2.raise_()
        self.gridLayoutWidget.raise_()
        self.currentSuccess.raise_()
        self.totalSuccess.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.lLeverPos.raise_()
        self.rLeverPos.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.mLeft.raise_()
        self.mRight.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "lever-arena v1.0"))
        self.label_2.setText(_translate("MainWindow", "Study"))
        self.study.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Animal #"))
        self.animal.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Logging"))
        self.logging.setText(_translate("MainWindow", "Logging"))
        self.lLever.setText(_translate("MainWindow", "3200"))
        self.rLever.setText(_translate("MainWindow", "3200"))
        self.label_6.setText(_translate("MainWindow", "Right Lever"))
        self.label_5.setText(_translate("MainWindow", "Left Lever"))
        self.lEnable.setText(_translate("MainWindow", "Left Enable"))
        self.rEnable.setText(_translate("MainWindow", "Right Enable"))
        self.mSuccesses.setText(_translate("MainWindow", "3"))
        self.label_7.setText(_translate("MainWindow", "Success #"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.mSet.setText(_translate("MainWindow", "set"))
        self.mButton8.setText(_translate("MainWindow", "8"))
        self.mButton9.setText(_translate("MainWindow", "9"))
        self.mButton7.setText(_translate("MainWindow", "7"))
        self.mButton10.setText(_translate("MainWindow", "10"))
        self.mButton6.setText(_translate("MainWindow", "6"))
        self.mButton15.setText(_translate("MainWindow", "15"))
        self.mButton12.setText(_translate("MainWindow", "12"))
        self.mButton14.setText(_translate("MainWindow", "14"))
        self.mButton13.setText(_translate("MainWindow", "13"))
        self.mButton11.setText(_translate("MainWindow", "11"))
        self.mButton1.setText(_translate("MainWindow", "1"))
        self.mButton2.setText(_translate("MainWindow", "2"))
        self.mButton5.setText(_translate("MainWindow", "5"))
        self.mButton3.setText(_translate("MainWindow", "3"))
        self.mButton4.setText(_translate("MainWindow", "4"))
        self.mReward.setText(_translate("MainWindow", "Reward"))
        self.mFlush.setText(_translate("MainWindow", "Flush"))
        self.mAdvance.setText(_translate("MainWindow", "Advance"))
        self.label_4.setText(_translate("MainWindow", "Success"))
        self.label_8.setText(_translate("MainWindow", "Total"))
        self.label_9.setText(_translate("MainWindow", "Left Lever"))
        self.label_10.setText(_translate("MainWindow", "Right Lever"))
        self.mLeft.setText(_translate("MainWindow", "Set Left"))
        self.mRight.setText(_translate("MainWindow", "Set Right"))

